// @flow
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS';
export const SET_LANGUAGE_FAILURE = 'SET_LANGUAGE_FAILURE';

export const GET_ADDRESSES = 'GET_ADDRESSES';
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
export const GET_ADDRESSES_FAILURE = 'SET_LANGUAGE_FAILURE';
