# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auxxa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Auxxa

  target 'Auxxa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'AuxxaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Auxxa-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Auxxa-tvOS

end
