// @flow
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const EDIT_CART = 'EDIT_CART';
export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS';
export const EDIT_CART_FAILURE = 'EDIT_CART_FAILURE';

export const REMOVE_CART = 'REMOVE_CART';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const REMOVE_CART_FAILURE = 'REMOVE_CART_FAILURE';

export const ADD_TO_WISH_LIST = 'ADD_TO_WISH_LIST';
export const ADD_TO_WISH_LIST_SUCCESS = 'ADD_TO_WISH_LIST_SUCCESS';
export const ADD_TO_WISH_LIST_FAILURE = 'ADD_TO_WISH_LIST_FAILURE';

export const REMOVE_FROM_WISH_LIST = 'REMOVE_FROM_WISH_LIST';
export const REMOVE_FROM_WISH_LIST_SUCCESS = 'REMOVE_FROM_WISH_LIST_SUCCESS';
export const REMOVE_FROM_WISH_LIST_FAILURE = 'REMOVE_FROM_WISH_LIST_FAILURE';

export const GET_WISH_LIST = 'GET_WISH_LIST';
export const GET_WISH_LIST_SUCCESS = 'GET_WISH_LIST_SUCCESS';
export const GET_WISH_LIST_FAILURE = 'GET_WISH_LIST_FAILURE';
