export default enStrings = {
    LOGIN_TEXT: 'Your greatest shopping experience awaits you.',
    SIGN_IN: 'Sign in',
    NEW_TO_THIS: 'New to this?',
    ALREADY_MEMBER: 'Already a member?',
    SIGN_UP: 'Sign up',
    SIGN_IN_TO_CONTINUE: 'Sign in to continue.',
    EMAIL: 'E-mail',
    PASSWORD: 'Password',
    FORGOT_PASSWORD: 'Forgot Password?',
    PRODUCT_DETAILS: 'Product Details',
    ALL_CATEGORIES: 'All Categories',
    DESCRIPTION: 'Description',
    STORE_DETAILS: 'Store Details',
    CONTACT_SELLER: 'Contact Seller',
    RETURN_POLICY: 'Return Policy',
    RETURN_TEXT: 'Returns accepted if the product is not as described.',
    BUYER_PROTECTION: 'Buyer Protection',
    BUYER_TEXT: 'To ensure that every buyer is protected when purchasing from arcmall, we have the following refund options. \n\n' + 
    '- Full refund if you don\'t reviever your item.\n- Full or partial refund if the item is not as described or is damaged.',
    SOMETHING_WENT_WRONG: 'Something went wrong. Please try again later.',
    REVIEWS: 'Reviews',
    SHOW_ALL: 'Show All',
    FORGET_PASSWORD:'Forgot password?',
    WISH_LIST:"Wish List",
    PAYMENT_METHOD:"Payment method",
    DESCRIPTION:"Description",
    SHIPPING_INFORMATION:"Shipping information",
    SHIPPING_ADDRESS:"Shipping address",
    BILLING_ADDRESS:"Billing address",
    RETURN_POLICY:"Return Policy",
    BUYER_PROTECTION:"Buyer Protection",
    LOG_OUT:"Log out",
    HOME:"Home",
    FIRST_NAME:'First Name',
    LAST_NAME:'Last Name',
    ADD_ITEM:'Add item',
    MY_PRODUCTS:'My products',
    CURRENCY: 'Currency',
    MY_PROFILE:'My Profile',
    LANGUAGE: 'Language',
    ENG_US: 'English (US)',
    CHINESE_SIMPLIFIED: '简体中文',
    COMPANY_NAME:'Company name',
    SEARCH: 'Search',
    SETTINGS: 'Settings',
    ADD: 'Add',
    SEE_MORE: 'See more',
    SELECT_YOUR_ROLE: 'Select your role',
    SELECT_ROLE_DESC: 'Signing up as a Buyer lets you purchase items and Signing up as a Seller allows you to both purhase and set up your own store.',
    SIGN_AS_BUYER_DESC: 'A wonderful collection of products awaits you.Let\'s get your all set up to explore a world of glamourous fashion',
    YOUR_ACCOUNT: 'Your Account',
    PROCESSING: 'Processing',
    SHIPPED: 'Shipped',
    COMPLETED: 'Completed',
    SELECT: 'Select',
    NO_ITEMS: 'Sorry, there are no items.',
    YOUR_CART: 'Your Cart',
    CHECKOUT: 'Checkout',
    PAY_WITH_PAYPAL: "Pay with Paypal",
    ITEMS: 'Items',
    LOGIN_TO_SEE: 'Please login to see content',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    EDIT_ACCOUNT_DETAILS: 'Edit Account Details',
    CHANGE_PASSWORD: 'Change Password',
    YOUR_SHIPPING_ADDRESS: 'Your Shipping Address',
    ORDER_CONFIRMATION: 'Order Confirmation',
    ORDER_HISTORY: 'Order History',
    MOBILE_NUMBER: 'Mobile Number',
    EDIT_PROFILE: 'Edit Profile',

}