export default enStrings = {
    LOGIN_TEXT: 'Your greatest shopping experience awaits you.',
    SIGN_IN: 'Sign in',
    NEW_TO_THIS: 'New to this?',
    ALREADY_MEMBER: 'Already a member?',
    SIGN_UP: 'Sign up',
    SIGN_IN_TO_CONTINUE: 'Sign in to continue.',
    EMAIL: 'E-mail',
    PASSWORD: 'Password',
    FORGOT_PASSWORD: 'Forgot Password?',
    PRODUCT_DETAILS: 'Product Details',
    DESCRIPTION: 'Description',
    STORE_DETAILS: 'Store Details',
    CONTACT_SELLER: 'Contact Seller',
    RETURN_POLICY: 'Return Policy',
    RETURN_TEXT: 'Returns accepted if the product is not as described.',
    BUYER_PROTECTION: 'Buyer Protection',
    BUYER_TEXT: 'To ensure that every buyer is protected when purchasing from arcmall, we have the following refund options. \n\n' + 
    '- Full refund if you don\'t reviever your item.\n- Full or partial refund if the item is not as described or is damaged.',
    SOMETHING_WENT_WRONG: 'Something went wrong. Please try again later.',
    REVIEWS: 'Reviews',
    SHOW_ALL: 'Show All',
}