export default zhStrings = {

    LOGIN_TEXT: 'Your greatest shopping experience awaits you.',
    SIGN_IN: '签到',
    NEW_TO_THIS: 'New to this?',
    ALREADY_MEMBER: 'Already a member?',
    SIGN_UP: '注册',
    SIGN_IN_TO_CONTINUE: 'Sign in to continue.',
    EMAIL: '电子邮件地址',
    PASSWORD: '密码',
    FORGOT_PASSWORD: 'Forgot Password?',
    PRODUCT_DETAILS: 'Product Details',
    DESCRIPTION: 'Description',
    STORE_DETAILS: 'Store Details',
    CONTACT_SELLER: 'Contact Seller',
    RETURN_POLICY: 'Return Policy',
    RETURN_TEXT: 'Returns accepted if the product is not as described.',
    BUYER_PROTECTION: 'Buyer Protection',
    BUYER_TEXT: 'To ensure that every buyer is protected when purchasing from arcmall, we have the following refund options. \n\n' + 
    '- Full refund if you don\'t reviever your item.\n- Full or partial refund if the item is not as described or is damaged.',
    SOMETHING_WENT_WRONG: 'Something went wrong. Please try again later.',
    SHOW_ALL: 'Show All',
    FORGET_PASSWORD:'忘记密码 ?',
    WISH_LIST:"愿望清单",
    PAYMENT_METHOD:"付款方法",
    DESCRIPTION:"描述",
    REVIEWS:"评测",
    SHIPPING_INFORMATION:"货运信息",
    SHIPPING_ADDRESS:"邮寄地址",
    BILLING_ADDRESS:"帐单地址",
    RETURN_POLICY:"退货政策",
    BUYER_PROTECTION:"Buyer Protection",
    LOG_OUT:"买家保护",
    HOME:"家",
    FIRST_NAME:'名字',
    LAST_NAME:'姓',
    ADD_ITEM:'新增项目',
    MY_PRODUCTS:'我的产品',
    CURRENCY: '货币',
    MY_PROFILE:'我的简历',
    LANGUAGE: '语言',
    ENG_US: '英语 (US)',
    CHINESE_SIMPLIFIED: '简体中文',
    COMPANY_NAME:'公司名',
    SEARCH:"搜索项目",
    SETTINGS: '设置',

    ADD: 'Add',
    SEE_MORE: 'See more',
    SELECT_YOUR_ROLE: 'Select your role',
    SELECT_ROLE_DESC: 'Signing up as a Buyer lets you purchase items and Signing up as a Seller allows you to both purhase and set up your own store.',
    SIGN_AS_BUYER_DESC: 'A wonderful collection of products awaits you.Let\'s get your all set up to explore a world of glamourous fashion',
    YOUR_ACCOUNT: 'Your Account',
    PROCESSING: 'Processing',
    SHIPPED: 'Shipped',
    COMPLETED: 'Completed',
    SELECT: 'Select',
    NO_ITEMS: 'Sorry, there are no items.',
    YOUR_CART: 'Your Cart',
    CHECKOUT: 'Checkout',
    PAY_WITH_PAYPAL: "Pay with Paypal",
    ITEMS: 'Items',
    LOGIN_TO_SEE: 'Please login to see content',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    EDIT_ACCOUNT_DETAILS: 'Edit Account Details',
    CHANGE_PASSWORD: 'Change Password',
    YOUR_SHIPPING_ADDRESS: 'Your Shipping Address',
    CATEGORIES: 'Categories',
    ITEM_DETAILS: 'Item Details',
    OPTIONS: 'Options',
    IMAGES: 'Images',
    ADD_IMAGES: 'Add Images',
    CANCEL: 'Cancel',
    ORDER_CONFIRMATION: 'Order Confirmation',
    ORDER_HISTORY: 'Order History',
    MOBILE_NUMBER: 'Mobile Number',
    EDIT_PROFILE: 'Edit Profile',
    STORE_PRODUCTS: 'Store Products',
    SHOP: 'Shop',
    ORDER_HISTORY:'Order History',
    PLACED_ON: 'Placed on',
    STATUS: 'Status',
    QUANTITY: 'Quantity',
    ADD_PRODUCT_NAME: 'Product Name',
    ADD_PRODUCT_DESC: 'Product Description (Be detailed)',
    ADD_PRODUCT_QUANTITY: 'Available Quantity',
    ADD_PRODUCT_PRICE: 'Item Price (USD)',
    ADD_PRODUCT_WEIGHT: 'Item Weight (KG)',
    ENTER_ALL_FIELDS: 'Please enter all fields.',
    ENTER_CATEGORY: 'Plase select a category. \n',
    ENTER_IMAGE: 'Plase select an image. \n';,
}